### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'embedding_size'

### ISSUE THREAD

**Issue by sharmahr** [akanimax/T2F#15]
When I run train_network.py,

I get the error:

Traceback (most recent call last):
  File "train_network.py", line 428, in <module>
    main(parse_arguments())
  File "train_network.py", line 381, in main
    device=device
TypeError: __init__() got an unexpected keyword argument 'embedding_size'

Does anyone know how to solve this?

**Comment by ulucsahin** [comment]
Unfortunately some methods are changed in pro_gan_pytorch and this code gives this error. What version of pro_gan_pytorch do we need?

**Comment by somanshreddy** [comment]
Downgrading to an earlier version of pro-gan-pth fixes this issue. 

Run the below command 
`pip install pro-gan-pth==1.3.3`
